source "https://rubygems.org"

gem "jekyll", "~> 4.3"

# GitHub Pages compatible plugins
group :jekyll_plugins do
  gem "jekyll-seo-tag"
end

# Syntax highlighting
gem "rouge"

# Windows and JRuby does not include zoneinfo files
gem "tzinfo-data", platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1", platforms: [:mingw, :mswin, :x64_mingw]
